engines:
  gofmt:
    enabled: true
  golint:
    enabled: true
  golint:
    enabled: true

ratings:
  paths:
    - "**.go"

# Ignore generated code.
exclude_paths:
- "go/vt/proto/"
- "go/vt/sqlparser/sql.go"

