# Use container-based infrastructure (see: http://docs.travis-ci.com/user/workers/container-based-infrastructure/).
sudo: false
language: go
go:
  - 1.4
addons:
  apt:
    packages:
    # NOTE: When you add a dependency, don't forget to add comment why it's necessary.
    - automake
    - libtool
    - memcached
    - python-dev
    - python-mysqldb
    - python-pip
    - python-virtualenv
    - libssl-dev
    - g++
    - git
    - pkg-config
    # installs libaio1 which is required by MariaDB 10.0 server package
    - libaio-dev
    # required by travis script below to measure CPU and memory usage
    - time
    # TODO(mberlin): Remove this when python-mysql is installable via the "apt" addon above.
    - python-dev
    # Optional dependency. Without a running syslog daemon, Vitess will keep complaining that it could not log events and spam the logs.
    - rsyslog
env:
  global:
    - MYSQL_FLAVOR=MariaDB
    - MYSQL_ROOT=$HOME/mysql
    - VT_MYSQL_ROOT=$MYSQL_ROOT/usr
    # Enable parallel compilation e.g. for gRPC.
    # (The Travis CI worker is allowed to use up to 2 cores, but as of 07/2015 4 parallel compilations is actually faster.)
    - MAKEFLAGS=-j4
    # TODO(mberlin): Remove this when python-mysql is installable via the "apt" addon above.
    - PYTHONPATH=$HOME/.local/lib/python2.7/site-packages
    # Run go build and test with -p 4 (i.e. up to 4 packages are compiled/tested in parallel).
    # As of 07/2015 this value works best in a Travis CI container.
    - VT_GO_PARALLEL=4
  matrix:
    - MAKE_TARGET=java_vtgate_client_test
    - MAKE_TARGET=unit_test_goveralls
    - MAKE_TARGET=small_integration_test
    - MAKE_TARGET=medium_integration_test
    - MAKE_TARGET=large_integration_test
    - MAKE_TARGET=queryservice_test
    - MAKE_TARGET=unit_test
before_install:
  - bash travis/download_mariadb.sh
  # TODO(mberlin): Remove this when python-mysql is installable via the "apt" addon above.
  - PATH=$PATH:$MYSQL_ROOT/usr/bin LDFLAGS="-L$MYSQL_ROOT/usr/lib" pip install --user mysql-python
install:
  - bash -v bootstrap.sh
script:
  - source dev.env
  # Log GOMAXPROCS (should be 2 as of 07/2015).
  - go run travis/log_gomaxprocs.go
  - |
      travis_retry /usr/bin/time -f "CPU: %P Memory: %M kB" make build $MAKE_TARGET
