apiVersion: v1
kind: ReplicationController
metadata:
  name: etcd-{{cell}}
spec:
  replicas: {{replicas}}
  template:
    metadata:
      labels:
        component: etcd
        cell: {{cell}}
        app: vitess
    spec:
      volumes:
        - name: certs
          # Uncomment one of the following lines to configure the location
          # of the root certificates file on your host OS. We need this so
          # we can import it into the container OS.
          # If your host OS is Fedora/RHEL:
          #hostPath: {path: /etc/pki/tls/certs/ca-bundle.crt}
          # If your host OS is Debian/Ubuntu/Gentoo:
          hostPath: {path: /etc/ssl/certs/ca-certificates.crt}
      containers:
        - name: etcd
          image: vitess/etcd:v2.0.13-lite
          livenessProbe:
            httpGet:
              path: /v2/keys/
              port: 4001
            initialDelaySeconds: 30
            timeoutSeconds: 5
          volumeMounts:
            - name: certs
              readOnly: true
              # Mount root certs from the host OS into the location
              # expected for our container OS (Debian):
              mountPath: /etc/ssl/certs/ca-certificates.crt
          resources:
            limits:
              memory: "128Mi"
              cpu: "100m"
          command:
            - bash
            - "-c"
            - >-
              ipaddr=$(hostname -i)

              if [ "{{cell}}" != "global" ]; then
              until etcdctl -C "http://etcd-global:4001"
              set "/vt/cells/{{cell}}" "http://etcd-{{cell}}:4001"; do
              echo "[$(date)] waiting for global etcd to register cell '{{cell}}'";
              sleep 1;
              done;
              fi

              etcd -name $HOSTNAME -discovery {{discovery}}
              -advertise-client-urls http://$ipaddr:4001
              -initial-advertise-peer-urls http://$ipaddr:7001
              -listen-client-urls http://$ipaddr:4001
              -listen-peer-urls http://$ipaddr:7001

