apiVersion: v1
kind: ReplicationController
metadata:
  name: etcd-{{cell}}
  labels:
    name: etcd
    cell: {{cell}}
spec:
  replicas: {{replicas}}
  selector:
    name: etcd
    cell: {{cell}}
  template:
    metadata:
      labels:
        name: etcd
        cell: {{cell}}
    spec:
      volumes:
        - name: certs
          # Uncomment one of the following lines to configure the location
          # of the root certificates file on your host OS. We need this so
          # we can import it into the container OS.
          # If your host OS is Fedora/RHEL:
          #hostPath: {path: /etc/pki/tls/certs/ca-bundle.crt}
          # If your host OS is Debian/Ubuntu/Gentoo:
          hostPath: {path: /etc/ssl/certs/ca-certificates.crt}
      containers:
        - name: etcd
          image: vitess/etcd:v2.0.13-lite
          volumeMounts:
            - name: certs
              readOnly: true
              # Mount root certs from the host OS into the location
              # expected for our container OS (Debian):
              mountPath: /etc/ssl/certs/ca-certificates.crt
          command:
            - bash
            - "-c"
            - >-
              ipaddr=$(hostname -i)

              global_etcd=$ETCD_GLOBAL_SERVICE_HOST:$ETCD_GLOBAL_SERVICE_PORT

              cell="{{cell}}" &&
              local_etcd_host_var="ETCD_${cell^^}_SERVICE_HOST" &&
              local_etcd_port_var="ETCD_${cell^^}_SERVICE_PORT" &&
              local_etcd=${!local_etcd_host_var}:${!local_etcd_port_var}

              if [ "{{cell}}" != "global" ]; then
              until etcdctl -C "http://$global_etcd"
              set "/vt/cells/{{cell}}" "http://$local_etcd"; do
              echo "[$(date)] waiting for global etcd to register cell '{{cell}}'";
              sleep 1;
              done;
              fi

              etcd -name $HOSTNAME -discovery {{discovery}}
              -advertise-client-urls http://$ipaddr:4001
              -initial-advertise-peer-urls http://$ipaddr:7001
              -listen-client-urls http://$ipaddr:4001
              -listen-peer-urls http://$ipaddr:7001

