kind: ReplicationController
apiVersion: v1
metadata:
  name: guestbook
  labels:
    name: guestbook
spec:
  replicas: 3
  selector: {name: guestbook}
  template:
    metadata:
      labels: {name: guestbook}
    spec:
      containers:
        - name: guestbook
          image: vitess/guestbook
          ports:
            - name: http-server
              containerPort: 8080

