kind: Service
apiVersion: v1
metadata:
  name: vtctld
  labels:
    name: vtctld
spec:
  ports:
    - port: 15000
      targetPort: 15000
      nodePort: 30000
  selector: {name: vtctld}
  type: NodePort

