kind: Pod
apiVersion: v1beta3
metadata:
  name: vtgate-{{uid}}
  labels: {name: vtgate}
spec:
  containers:
    - name: vtgate
      image: vitess/root
      volumeMounts:
        - name: syslog
          mountPath: /dev/log
        - name: vtdataroot
          mountPath: /vt/vtdataroot
      command:
        - sh
        - "-c"
        - >-
          mkdir -p $VTDATAROOT/tmp &&
          chown -R vitess /vt &&
          su -p -c "/vt/bin/vtgate
          -topo_implementation etcd
          -etcd_global_addrs http://$ETCD_GLOBAL_SERVICE_HOST:$ETCD_GLOBAL_SERVICE_PORT
          -log_dir $VTDATAROOT/tmp
          -alsologtostderr
          -port 15001
          -cell test" vitess
      env:
        - name: GOMAXPROCS
          value: "16"
  volumes:
    - name: syslog
      hostPath: {path: /dev/log}
    - name: vtdataroot
      {{vtdataroot_volume}}

