kind: ReplicationController
apiVersion: v1
metadata:
  name: vtgate
  labels: {name: vtgate}
spec:
  replicas: {{replicas}}
  selector: {name: vtgate}
  template:
    metadata:
      labels: {name: vtgate}
    spec:
      containers:
        - name: vtgate
          image: vitess/lite
          volumeMounts:
            - name: syslog
              mountPath: /dev/log
            - name: vtdataroot
              mountPath: /vt/vtdataroot
          command:
            - sh
            - "-c"
            - >-
              mkdir -p $VTDATAROOT/tmp &&
              chown -R vitess /vt &&
              su -p -c "/vt/bin/vtgate
              -topo_implementation etcd
              -etcd_global_addrs http://$ETCD_GLOBAL_SERVICE_HOST:$ETCD_GLOBAL_SERVICE_PORT
              -log_dir $VTDATAROOT/tmp
              -alsologtostderr
              -port 15001
              -tablet_protocol grpc
              -cell test" vitess
      volumes:
        - name: syslog
          hostPath: {path: /dev/log}
        - name: vtdataroot
          emptyDir: {}

